name: Go Format

on:
  push:
    branches: [ 'main', 'release-*' ]
  pull_request:
    branches: [ 'main', 'release-*' ]

permissions:
  contents: read
  
jobs:

  format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: 1.23
          cache-dependency-path: v2/go.sum
        id: go

      - name: Go Format
        shell: bash
        run: |
          gofmt -s -w $(find -type f -name '*.go' -print)

      - name: Verify
        shell: bash
        run: |
          if [[ $(git diff-index --name-only HEAD --) ]]; then
              echo "Found diffs in:"
              git diff-index --name-only HEAD --
              echo "${{ github.repository }} is out of style. Please run go fmt."
              exit 1
          fi
          echo "${{ github.repository }} is formatted correctly."
